services:
  native-application:
    image: "udemy-spring-reactive:1.1"
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"